# Generated by Django 4.2 on 2025-11-05 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licenseManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensemanager',
            name='max_devices',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licenseManager.licensemanager')),
            ],
            options={
                'unique_together': {('license', 'machine_id')},
            },
        ),
    ]
